server:
  port: 1001
app:
  auth-service:
    url: http://AUTHSERVICE

eureka:
  client:
    service-url:
      defaultZone: '${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}'
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthenticationFilter
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthenticationFilter
        - id: sales-service
          uri: lb://SALESSERVICE
          predicates:
            - Path=/api/v1/sales/**
          filters:
            - AuthenticationFilter
        - id: product-service
          uri: lb://PRODUCTSERVICE
          predicates:
            - Path=/api/v1/product/**
          filters:
            - AuthenticationFilter

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
